export const PICKUP_LOCATION_SEARCH = 'PICKUP_LOCATION_SEARCH'
export const PICKUP_LOCATION_RESULT = 'PICKUP_LOCATION_RESULT'
export const PICKUP_LOCATION_SELECT = 'PICKUP_LOCATION_SELECT'

export const DESTINATION_LOCATION_SEARCH = 'DESTINATION_LOCATION_SEARCH'
export const DESTINATION_LOCATION_RESULT = 'DESTINATION_LOCATION_RESULT'
export const DESTINATION_LOCATION_SELECT = 'DESTINATION_LOCATION_SELECT'


export const DIRECTION_REQUEST = 'DIRECTION_REQUEST'
export const DIRECTION_RESULT = 'DIRECTION_RESULT'

export const PATH_REQUEST = 'PATH_REQUEST';
export const PATH_RESULT = 'PATH_RESULT';

export const CURRENT_LOCATION_REQUEST = 'CURRENT_LOCATION_REQUEST'
export const CURRENT_LOCATION_RESULT = 'CURRENT_LOCATION_RESULT'

export const TOTAL_DISTANCE = 'TOTAL_DISTANCE'
export const TOTAL_DURATION = 'TOTAL_DURATION'




