export const GET_VEHICLE = 'GET_VEHICLE'
export const SHOW_VEHICLE = 'SHOW_VEHICLE'

export const GET_AVAILABLE_VEHICLES = 'GET_AVAILABLE_VEHICLES'
export const SHOW_AVAILABLE_VEHICLES = 'SHOW_AVAILABLE_VEHICLES'

export const  GET_SELECTED_VEHICLE = 'GET_SELECTED_VEHICLE'
export const SHOW_SELECTED_VEHICLE = 'SHOW_SELECTED_VEHICLE'

export const EMPTY_VEHICLES = 'EMPTY_VEHICLES'
